version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: diary
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
